import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { useNavigation } from '../../components/NavigationContext';

export default function DisclaimerPage() {
    const { navigate } = useNavigation();
    return (
        <div className="max-w-4xl mx-auto bg-white p-8 md:p-12 rounded-2xl border border-stone-200 shadow-sm">
            <button 
              onClick={() => navigate('HOME')}
              className="flex items-center gap-2 text-stone-500 hover:text-orange-600 transition-colors mb-6 text-sm font-medium"
            >
              <ArrowLeft size={16} /> Back to Home
            </button>
            <div className="prose prose-stone max-w-none prose-h1:font-serif prose-h2:font-serif">
                <h1 className="title-float-effect">Disclaimers</h1>
                <p className="text-sm text-stone-500">Last Updated: {new Date().toLocaleDateString()}</p>
                
                <h2>Nutritional & Health Disclaimer</h2>
                <p>The nutritional information on Recipe Atlas is generated by our system and is for informational purposes only. It is an estimate and not a substitute for professional medical advice. Always seek the advice of a qualified health provider for any questions regarding a medical condition or dietary needs.</p>

                <h2>Affiliate Disclosure</h2>
                <p>This site contains affiliate links. If you make a purchase through these links, Recipe Atlas may receive a commission at no extra cost to you. This supports our platform and allows us to continue creating content. We only recommend products we believe in.</p>
                
                <h2>Content Disclaimer</h2>
                <p>All content is generated by our system. While we strive for accuracy, errors may occur. Users should use their best judgment and standard cooking safety practices. Recipe Atlas is not liable for any outcomes from the use of its content.</p>
            </div>
        </div>
    );
}
